spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train_booking_system
    username: root
    password: "@Yushmanraj7272"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: sahilkum097@gmail.com
    password: twchxxyclaqccqeg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

razorpay:
   key:
      id: rzp_test_SdpP4NW3uQydrF
      secret: 7yE14fgbgrfRr2EwxCmWnc7p

rapidapi:
  key: 24515135a1msh2c534530def53a2p183c23jsn050c84f183c7
  host: irctc-train-api.p.rapidapi.com


 
            